### ISSUE TITLE
xrange not defined

### ISSUE THREAD

**Issue by alain2208** [hugorut/neural-cli#2]
hi took your files and put it in d: folder 
each i try i got a xrange not defined running python3.52 windows
it starts show some values after few seconsds crasdhed
installed with PIP
neuralcli train d:/neural/train.csv d:/neural/expected.csv  --normalize=true
1.57867334226                    Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\neuralcli.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\anaconda3\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\anaconda3\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\anaconda3\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\neuralcli\cli.py", line 35, in train
    nn.accuracy()
  File "c:\anaconda3\lib\site-packages\neuralcli\neuralnet.py", line 318, in accuracy
    for x in xrange(examples):
NameError: name 'xrange' is not defined

**Comment by hugorut** [comment]
@alain2208 another python3 compatibility issue, will put out a fix at lunch, thanks for letting me know

**Comment by alain2208** [comment]
i try to replace by range on my pc  and seems to work

**Comment by hugorut** [comment]
yeah just pushed a fix now download the latest 1.5 version using pip

**Comment by hugorut** [comment]
thanks, i'm going to close, but let me know if you run into any more issues

**Comment by hugorut** [comment]
also with the example dataset included you don't need to normalize so don't included the `--normalize=true` flag 👍

**Comment by alain2208** [comment]
yes saw the result is very bad when normalize. Seems it's ok now. very quick react
