### ISSUE TITLE
"Can't create weekday with n == 0" issue?

### ISSUE THREAD

**Issue by asidapara** [hugorut/neural-cli#5]
Hi there, 

I tried to run neuralcli with an input CSV file with 10000 rows and 200 columns and an output of 10000 rows and 100 columns. I got the following issue-- not sure if it's on my end or a bug with the library itself.

 `Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/neuralcli", line 7, in <module>
    from neuralcli.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/neuralcli/cli.py", line 2, in <module>
    from .neuralnet import NeuralNet
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/neuralcli/neuralnet.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/pyplot.py", line 37, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/figure.py", line 40, in <module>
    from matplotlib.axes import Axes, SubplotBase, subplot_class_factory
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axes/__init__.py", line 4, in <module>
    from ._subplots import *
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axes/_subplots.py", line 10, in <module>
    from matplotlib.axes._axes import Axes
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axes/_axes.py", line 24, in <module>
    import matplotlib.dates as _  # <-registers a date unit converter
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/dates.py", line 125, in <module>
    from dateutil.rrule import (rrule, MO, TU, WE, TH, FR, SA, SU, YEARLY,
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dateutil/rrule.py", line 55
    raise ValueError, "Can't create weekday with n == 0"`

**Comment by hugorut** [comment]
could you post the command line input that you used, many thanks

**Comment by asidapara** [comment]
Looks like I accidentally inputted two input files... my bad

**Comment by ruelabion** [comment]
sudo pip3 install --upgrade python-util
Src: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwiaqduYuPnVAhWJspQKHf7JB-UQFggtMAE&url=http%3A%2F%2Fblog.csdn.net%2Fyzf0011%2Farticle%2Fdetails%2F73250107&usg=AFQjCNENKcTOoW7fssQf6jRnUjLTlIGrBw
